---
# tasks file for ansible-role-upgrade-all-packages

- name: Upgrade all packages in RedHat systems
  block:

    - name: RedHat/CentOS | upgrade all packages (RedHat)
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: true
      tags:
        - skip_ansible_lint

    - name: RedHat/CentOS | Make sure yum-utils is installed so we can use command "needs-restarting"
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: RedHat/CentOS | Check if the machine needs a reboot
      ansible.builtin.command: needs-restarting -r
      ignore_errors: true
      changed_when: false
      register: needs_restarting_output

    - name: RedHat/CentOS | Reboot the machine if required
      ansible.builtin.reboot:
      when:
        - needs_restarting_output.rc != 0
        - upgrade_all_packages_reboot | bool
        - not ansible_virtualization_type == "docker"       # skip reboot if this is a CI test in a container
        - not ansible_virtualization_type == "containerd"   # skip reboot if this is a CI test in a container

  when: ansible_os_family == "RedHat"


- name: Upgrade all packages in Debian systems
  block:

    - name: Debian/Ubuntu | Install aptitude is this is a debian/ubuntu system
      ansible.builtin.apt:
        pkg: aptitude
        state: present
        update_cache: true

    - name: Debian/Ubuntu | upgrade all packages (Debian)
      ansible.builtin.apt:
        name: '*'
        state: latest
      register: upgraded_packages
      tags:
        - skip_ansible_lint

    - name: Debian/Ubuntu | Check if file /var/run/reboot-required exists
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Debian/Ubuntu | Reboot the machine if needed
      ansible.builtin.reboot:
      when:
        - reboot_required_file.stat.exists
        - upgrade_all_packages_reboot | bool
        - not ansible_virtualization_type == "docker"       # skip reboot if this is a CI test in a container
        - not ansible_virtualization_type == "containerd"   # skip reboot if this is a CI test in a container

  when: ansible_os_family == "Debian"
